### ISSUE TITLE
Initial API Spec Draft in Open API 3.0 format

### ISSUE THREAD

**Issue by Therecanbeonlyone1969** [eea-oasis/baseline-standard#1]

**Comment by kthomas** [comment]
This issue most certainly would be split up under normal circumstances but it aims to capture a significant amount of prior work to standup the formal draft specification based on [this](https://docs.google.com/spreadsheets/d/1ecLXGb1BnDfTZfwo-mULAUMTEWMxQt0ibOIazEicx9g/edit) set of requirements.

**Comment by Consianimis** [comment]
This should include both interfaces and data model(s).
