### ISSUE TITLE
Clean up how references are presented

### ISSUE THREAD

**Issue by chaals** [eea-oasis/baseline-standard#102]
At the moment there are some references inline, some collected "spec-style" at the end but without being linkable.

I suggest we use a consistent style, e.g.

> ... Make identifiers conformant to W3C DID spec [[ref-DID]](#ref-DID), especially [section 4 Fancy Tricks](https://w3.org/TR/did/#sec-fancy-tricks)

So that all references to entire documents link to the references section, and inline references are to specific sections, as additional links.

If we're agreed, you can assign this to me and I'll make a pull request

**Comment by anaisofranc** [comment]
@chaals - I had raised a question related to this unfortunately I did not get the answer in time before submission :)

**Comment by Therecanbeonlyone1969** [comment]
@chaals ... please use this branch where the WG is collectively working to correct the remaining editorial issues. https://github.com/eea-oasis/baseline-standard/blob/pr/101/core/baseline-core-v1.0-psd01.md

**Comment by Therecanbeonlyone1969** [comment]
done with #114
