### ISSUE TITLE
Update readme with 'Draft Release 0.1' and date (11/17/2021)

### ISSUE THREAD

**Issue by GoldenBit0** [eea-oasis/baseline-standard#106]
Update readme with 'Draft Release 0.1' and date (11/17/2021)

**Comment by Therecanbeonlyone1969** [comment]
Updated in all readme.md files and the head of the individual spec docs. see current working branch https://github.com/eea-oasis/baseline-standard/blob/pr/101/core/baseline-core-v1.0-psd01.md

**Comment by Therecanbeonlyone1969** [comment]
done with #114
