### ISSUE TITLE
Clearly and accurately describe the current status and proposing group's expectations for its future

### ISSUE THREAD

**Issue by GoldenBit0** [eea-oasis/baseline-standard#110]
The document MUST clearly and accurately describe its current status, and the proposing group’s expectations for its future (e.g. publishing schedule, final destiny, …)

**Comment by Therecanbeonlyone1969** [comment]
@GoldenBit0 ... started new editorial branch ... addressed this issue here ... https://github.com/eea-oasis/baseline-standard/blob/pr/101/README.md#status

**Comment by Therecanbeonlyone1969** [comment]
closing issue since addressed in updated branch
