### ISSUE TITLE
Update document with IETF's BCP14

### ISSUE THREAD

**Issue by GoldenBit0** [eea-oasis/baseline-standard#112]
The document MUST use IETF’s BCP14, i.e. RFC2119 and RFC8174 terminology for conformance

**Comment by Therecanbeonlyone1969** [comment]
@chaals ... please, provide examples of non-compliance and required correction. The group is unsure where the issue is.

**Comment by chaals** [comment]
As far as I can tell, the spec implements this in practice, so it's just a case of putting a reference in to make it clear (and checking to see if something fell through the editorial nets, but that's no big deal).

**Comment by Therecanbeonlyone1969** [comment]
done with #114
