### ISSUE TITLE
Research on testing companies 

### ISSUE THREAD

**Issue by GoldenBit0** [eea-oasis/baseline-standard#113]
Research testing companies and compile findings to present at next session.

Notes from 11/18/21 standards call on topic:
- fully open source (any company who wants to pass certification test can do so and publish out report), to be fully certified needs to be done by an independent body
- company will need to do test harness, take legal liability, do security audit
- https://www.dnv.com/oilgas/joint-industry-projects/index.html, https://standards.ieee.org/standard/1028-2008.html, SQS, TSC, EY, Accenture

**Comment by GoldenBit0** [comment]
Update: 
 - Preliminary test company research complete given scope of my knowledge, will address at 12/2 to discuss next steps 
 - Time set up with EEA/Oasis on 12/7 to discuss if standards bodies could be certifying bodies

**Comment by Therecanbeonlyone1969** [comment]
@Therecanbeonlyone1969 will write a RFP for a test harness and test fixtures by the next meeting (12/16/2021)

**Comment by Therecanbeonlyone1969** [comment]
can be closed
