### ISSUE TITLE
Differentiate business vs code requirements?

### ISSUE THREAD

**Issue by chaals** [eea-oasis/baseline-standard#115]
There are some requirements that seem to be untestable at the level of code, and further don't seem likely to have an impact on whether a BPI _functions_ correctly.

E.g. If two organisations don't meet

> **[R3]** There MUST be a legally binding contract, however simple and temporary, before a commercial transaction — such as an order — between parties takes place.

is there anything in the code, or in executing the code, that will be different to when the condition is met?

If there is no difference, then it might be helpful to define different types of requirement. That way, people trying to write a spec-compliant implementation aren't left wondering how they ensure their code meets the requirement.

**Comment by Therecanbeonlyone1969** [comment]
@chaals ... all the requirements are testable in code. Just need to be clever how this is done. Again see the started implementation guide for examples to make "business" requirements testable in code.

**Comment by chaals** [comment]
I cannot find the implementation guide. I would like a pointer, and two more weeks, to understand this before the issue is closed, please

**Comment by Therecanbeonlyone1969** [comment]
stale issue -> closing for the time being
