### ISSUE TITLE
Is one of R6 and R7 redundant?

### ISSUE THREAD

**Issue by chaals** [eea-oasis/baseline-standard#117]
R6 requires a commercial document is represented electronically, R7 that it is represented in a BPI.

Is there a way to have a commercial document represented in a BPI other than electronically? If not, it seems like R6 is unnecessary.

**Comment by Therecanbeonlyone1969** [comment]
@chaals ... no it is not redundant. R6 ensures the existence of an, ideally, human-readable version, and R7 says that this version must be represented in a BPI. If you only have a paper version of a commercial document it is hard to implement that in a BPI in a compact, processing-friendly form, while also meeting the human need to be able to read that document electronically and reference it in the BPI representation. This comes back to my comment to your issue #116  (R2)

**Comment by Therecanbeonlyone1969** [comment]
@chaals ... per decision in WG meeting on 1/27 ... either reply to the response above or the issue will be closed at the next WG meeting.
