### ISSUE TITLE
Tighten up use of "commercial document"

### ISSUE THREAD

**Issue by chaals** [eea-oasis/baseline-standard#130]
In general, "commercial document" is a term used with a defined meaning.

This meaning should be in the glossary. It would also help immensely if there were a clear example given at its definition, such as a Purchase Order or Invoice. That is what I understand is meant from reading the spec, and is given as an example when the term is used.

Also, in the text of section 2.3 it is used in what appears to be a different sense:

> Such legal, commercial documents may be presented as a combination of one or more of the following:

The wording here should be changed to avoid ambiguity.

**Comment by GoldenBit0** [comment]
2/24/22 Standards Call:
Pending response

**Comment by Therecanbeonlyone1969** [comment]
Closing. Addressed with merged PR https://github.com/eea-oasis/baseline-standard/pull/173
