### ISSUE TITLE
Use of "Systems of Record" in 1. Introduction

### ISSUE THREAD

**Issue by atoulme** [eea-oasis/baseline-standard#132]
The specification refers to "Systems of Record", as a capitalized term, without definition. Please provide a definition for the term or use the wording provided in the abstract.

**Comment by GoldenBit0** [comment]
2/24/22 Standards Call:
Editorial suggestion

**Comment by Therecanbeonlyone1969** [comment]
Closing. Addressed with merged PR https://github.com/eea-oasis/baseline-standard/pull/173
