### ISSUE TITLE
Clarify section 2.3

### ISSUE THREAD

**Issue by atoulme** [eea-oasis/baseline-standard#133]
This section documents commercial and legal binding contracts, but it's unclear to me why this is specified.

For example, I could see contracts and agreements with no commercial binding legal documents take place inside a company.

Companies responding to bids, tenders, and requests for proposal may also interact without a commercial agreement in place.

It appears non-disclosure agreements could be captured in a baseline workflow as well for example.

== 

The requirement D1 says: "The contract SHOULD be in an electronic form."
However, requirement R6 says: "A commercial document MUST be represented as an electronic record.".

Would you please clarify what this mean in this context? Does it mean that the formal contract is converted to code, or is that it is available in PDF form? How should one interpret SHOULD in this context?

**Comment by GoldenBit0** [comment]
2/24/22 Standards Call:

- Issue also addressed here, https://github.com/eea-oasis/baseline-standard/issues/130
- Needs to be addressed
