### ISSUE TITLE
R22 - define publicly accessible manner

### ISSUE THREAD

**Issue by atoulme** [eea-oasis/baseline-standard#137]
R22 states `Commercial Counterparties MUST publish their level of conformity (self-declaration or certification) with the Baseline Protocol Standard in a publicly accessible manner.`

Who offers certification at this time? The document does not define the certification process or requirements.
What does self-declaration consist of?

What does publicly accessible manner mean in this context? Is access to be revoked if the operator no longer participate? Should declarations be collected and published by the Baseline community?

**Comment by chaals** [comment]
This seems more like deployment guidance for keeping your self secure. if people don't want to publicly tell the world which bits they get wrong, but are prepared to share that privately with a counterparty that seems more useful than encouraging exaggerated claims of conformance that will be open to public scrutiny...

**Comment by Therecanbeonlyone1969** [comment]
Defined Publicly Accessible here in this [PR](https://github.com/eea-oasis/baseline-standard/pull/174)

The spec defines different conformance levels, and R22 gives options on how to publish conformance ... the manner of which can be freely chosen by the counterparties depending on convenience and availability. It is important if counterparties operate their own BPI that other counterparties interacting with the stack understand what is supported, and at what level.

**Comment by Therecanbeonlyone1969** [comment]
Questions and comments answered. Closing issue.
