### ISSUE TITLE
2.6.2 paragraph on OFAC

### ISSUE THREAD

**Issue by atoulme** [eea-oasis/baseline-standard#138]
2.6.2 starts with this paragraph:
```
Commercial Counterparties must comply efficiently and effectively with requirements of regulatory frameworks, e.g., Office of Foreign Assets Control ("OFAC") of the US Department of the Treasury when employing new operational and commercial frameworks as laid out in this standard.
```

Would it be possible to understand why this is stated? How does this relate to operations in other regions of the world?
I note this does not come with a formal requirement. Is that on purpose?

**Comment by chaals** [comment]
This seems like deployment guidance not a normative spec requirement. Agree that it makes sense to describe it better fr the rest of the world.

**Comment by Therecanbeonlyone1969** [comment]
Closing. Addressed with merged PR https://github.com/eea-oasis/baseline-standard/pull/173
