### ISSUE TITLE
Unclear how to implement R23

### ISSUE THREAD

**Issue by atoulme** [eea-oasis/baseline-standard#139]
R23 states:
```
If required to meet particular third party requirements, (e.g., privacy or regulatory frameworks in different jurisdictions), a commercial counterparty MUST record a pseudonymous map of the supply chain that is required to fulfill the provisioning of a requests commercial State Object (products, services or assets) transacted on a BPI.
```

It is not clear where this requirement applies as it actually depends on external privacy or regulatory frameworks. It would be good to define whether a jurisdiction applies to a counterparty.

It's unclear to me what the `pseudonymous map of the supply chain` is. Is it a document, a graphic, a report?
What does a counterparty needs to do with such a map? Where should it be recorded?

Should that map be updated on an ongoing basis?

I don't understand how the map of the supply chain is required to "fulfill the provisioning of a requests commercial State Object". Please help clarify.

**Comment by Therecanbeonlyone1969** [comment]
Closing. Addressed with merged PR https://github.com/eea-oasis/baseline-standard/pull/173
