### ISSUE TITLE
2.7.1 Use of System-of-Record

### ISSUE THREAD

**Issue by atoulme** [eea-oasis/baseline-standard#140]
The paragraph opening 2.7.1 mentions "System-of-Record" when the term "System of Record" is defined in the glossary.

**Comment by chaals** [comment]
Rewriting this sentence might help.  I'm not sure how to read "existing system of record integrations"...

**Comment by Kasshern** [comment]
I believe this is due to the use of "Systems of Record" as a compound adjective, therefore becoming Systems-of-Record. 

Although in 7.4 the compound adjective "system-of-record" is used. 

Some reconciliation of letter casing within these compound adjectives should likely occur.

**Comment by Therecanbeonlyone1969** [comment]
Closing. Addressed with merged PR https://github.com/eea-oasis/baseline-standard/pull/173
