### ISSUE TITLE
Simplify requirement D10

### ISSUE THREAD

**Issue by atoulme** [eea-oasis/baseline-standard#141]
Requirement D10 states:

```
The Public Key Infrastructure (PKI) of a BPI SHOULD be decentralized.

Decentralized in this context means that there is no single point of failure in the PKI where possibly no participants are known to one another.
```

I propose that both sentences become one, without the use of the word decentralized:

```
The Public Key Infrastructure (PKI) of a BPI SHOULD have no single point of failure where possibly no participants are known to one another.
```

I would drop the word possibly:

```
The Public Key Infrastructure (PKI) of a BPI SHOULD have no single point of failure where no participants are known to one another.
```

I would want to use a positive definition rather than a negative definition:
```
The Public Key Infrastructure (PKI) of a BPI SHOULD ensure participants always know each other.
```

Please discuss - as you can see, I am interpreting the requirement as I try to clarify it.

**Comment by chaals** [comment]
Agree with Antine's final rewording proposal.

**Comment by Therecanbeonlyone1969** [comment]
Closing. Addressed with merged PR https://github.com/eea-oasis/baseline-standard/pull/173
