### ISSUE TITLE
D13 Legal Entity

### ISSUE THREAD

**Issue by atoulme** [eea-oasis/baseline-standard#143]
D13 uses the term `(Legal) Entity`. I don't understand why legal is placed in parens. The next line offers a definition of Legal Entity:
`In the context of this document, a Legal Entity is an individual, organization, or company that has legal rights and obligations.
`

Should the definition be moved to the glossary? It is also used in R9 with no definition.

**Comment by chaals** [comment]
As described, this is using "legal entity" in line with normal understanding, so removing the "in the context of this document..." sentence doesn't seem to change anything. (Another common term meaning this is "legal person")

**Comment by Therecanbeonlyone1969** [comment]
Closing. Addressed with merged PR https://github.com/eea-oasis/baseline-standard/pull/173
