### ISSUE TITLE
D10 and D15 duplicates?

### ISSUE THREAD

**Issue by atoulme** [eea-oasis/baseline-standard#145]
D10 states: 
`The Public Key Infrastructure (PKI) of a BPI SHOULD be decentralized.

Decentralized in this context means that there is no single point of failure in the PKI where possibly no participants are known to one another.`

D15 states:
`A credential utilized within one or more BPIs SHOULD be discoverable by a participant in said BPI(s).`

Are those requirements duplicates?

**Comment by chaals** [comment]
I don't think so. (I do think there is some other redundancy around D15 but I need to find time to raise the issue)

**Comment by Therecanbeonlyone1969** [comment]
Closing. Addressed with merged PR https://github.com/eea-oasis/baseline-standard/pull/173
