### ISSUE TITLE
R47 credential holder definition

### ISSUE THREAD

**Issue by atoulme** [eea-oasis/baseline-standard#146]
R47 states `See the W3C Verifiable Credential Standard [[W3C VC]](https://github.com/eea-oasis/baseline-standard/blob/main/core/baseline-core-v1.0-psd01.md#w3c-vc) for a definition of credential holder.`

Upon searching the document linked, no definition of credential holder appears (the term "credential holder" is not present in the document ?!).

The specification linked defines the term "holder". I'd be interested to compare the term to the definition of principal owner used elsewhere.

**Comment by Therecanbeonlyone1969** [comment]
will link term directly to W3C definitionv-> in PR

**Comment by Therecanbeonlyone1969** [comment]
Closing. Addressed with merged PR https://github.com/eea-oasis/baseline-standard/pull/173
