### ISSUE TITLE
R81 : elicit audit trail

### ISSUE THREAD

**Issue by atoulme** [eea-oasis/baseline-standard#149]
R81 states: `A BPI Subject Account MUST have a cryptographically verifiable audit trail from BPI Subject Account inception to its closure.`

Would you please clarify what a cryptographically veriable audit trail means here?
Does the audit trail contain the list of all the operations done by the BPI Subject Account? Does it contain all inbound requests as well? Does it contain successes and failures, such as attempts to use the BPI subject account incorrectly?
What does cryptographically verifiable mean here? Does it mean that there is a method by which one can verify the authenticity of elements of the audit trail? Is the consistency of the audit trail also verifiable?

Please help clarify and elicit requirements.

**Comment by Therecanbeonlyone1969** [comment]
Closing. Addressed with merged PR https://github.com/eea-oasis/baseline-standard/pull/173
