### ISSUE TITLE
R82: clarify key encryption

### ISSUE THREAD

**Issue by atoulme** [eea-oasis/baseline-standard#150]
R82 states: `A BPI Subject Account MUST be encrypted to and decrypted by one or more cryptographic keys only known to the BPI Subject Account holder.`

Does this mean that the account can be encrypted by multiple keys at once? Or does it mean that it can be encrypted by one of the keys available, using a criteria left to the implementer?

**Comment by Therecanbeonlyone1969** [comment]
@atoulme ... how about this? cc @chaals @humbitious 

[R82] A BPI Subject Account MUST be encrypted to and decrypted by a cryptographic key only known to the BPI Subject Account owner.

**Comment by Therecanbeonlyone1969** [comment]
Closing. Addressed with merged PR https://github.com/eea-oasis/baseline-standard/pull/173
