### ISSUE TITLE
5.3 Dead link

### ISSUE THREAD

**Issue by atoulme** [eea-oasis/baseline-standard#153]
5.3 has a dead link to https://github.com/eea-oasis/baseline-standard/blob/main/core/baseline-core-v1.0-psd01.md#28-baseline-protocol-reference-architecture, it should be https://github.com/eea-oasis/baseline-standard/blob/main/core/baseline-core-v1.0-psd01.md#27-baseline-protocol-reference-architecture instead.

**Comment by Therecanbeonlyone1969** [comment]
@atoulme ... will update in an upcoming PR. Thank you!

**Comment by Therecanbeonlyone1969** [comment]
Closing. Addressed with merged PR https://github.com/eea-oasis/baseline-standard/pull/173
