### ISSUE TITLE
R107 Signed JSON Web Token should be JSON Web Signature

### ISSUE THREAD

**Issue by atoulme** [eea-oasis/baseline-standard#162]
R107 mentions `Signed JSON Web Token (JWS) structure` tied to RFC7515, but this RFC defines a JSON Web Signature.

**Comment by Therecanbeonlyone1969** [comment]
@atoulme forgot to add RFC7519 as the definition of JSON Web Token 

`[R107] The signed unencrypted format MUST use a Signed JSON Web Token (JWS) structure following RFC7519 and following [[RFC7515](https://github.com/eea-oasis/baseline-standard/blob/main/core/baseline-core-v1.0-psd01.md#rfc7515)] for its digital signature.`

Good enough?

**Comment by atoulme** [comment]
OK!
