### ISSUE TITLE
D21 mention of the W3C DID document

### ISSUE THREAD

**Issue by atoulme** [eea-oasis/baseline-standard#164]
D21 states: `The digital signature used for the JWS and JWE of a BPI Message SHOULD be based on the public keys associated with a W3C DID in the W3C DID document.`

Would you please clarify what W3C DID Document is referred on here?

**Comment by Therecanbeonlyone1969** [comment]
@atoulme DID document examples can be found here ... https://www.w3.org/TR/did-core/#did-documents ... will update language  of D21 and accompanying text accordingly.

**Comment by Therecanbeonlyone1969** [comment]
Closing. Addressed with merged PR https://github.com/eea-oasis/baseline-standard/pull/173 ... see https://github.com/eea-oasis/baseline-standard/blob/main/core/baseline-core-v1.0-psd01.md#d21
