### ISSUE TITLE
R135 seems to duplicate R13

### ISSUE THREAD

**Issue by atoulme** [eea-oasis/baseline-standard#168]
R13 defines a requirement for end-to-end encryption, and R135 states `Privacy-preserving in this context means that all communications are end-to-end encrypted independent of the security properties of the transportation layer.`

**Comment by Therecanbeonlyone1969** [comment]
@atoulme ah yes, this might appear that way. However, R13 refers to the BPI internal communication, and R135 refers to communication between BPIs since it is in the interop section. 

Does that make sense or do you want an explicit reference to R13 below R135 for clarification?

**Comment by atoulme** [comment]
No strong opinion, should be fine as is.

**Comment by Therecanbeonlyone1969** [comment]
ok. then I will close the issue.
