### ISSUE TITLE
Testability Statements for Section 4 - BPI Abstraction Layers

### ISSUE THREAD

**Issue by Kasshern** [eea-oasis/baseline-standard#201]
Testability statements providing the degree that characteristics that provide for testing exist shall be added to all Requirements, Optional Requirements, and Conditional Requirements as text directly following the requirement and its explanation. 

**Assumptions:**
1. The degree to which economically feasible tests can be devised for determining whether the developed software will satisfy the requirements is taken into account while writing these statements

**Comment by chaals** [comment]
I think this is good, but it isn't very clear what a testability requirement is. Does it explain why the requirement is testable (which is what it seemed to be when I first came across it) or is it "how to test" (which I think is actually a more useful thing to have in the long run - although I think that will mean we end up rewriting some mor requirements)?

**Comment by Therecanbeonlyone1969** [comment]
@chaals Testability statements (why it is testable with possibly a how-to). Definitely not requirements!

cc @Kasshern

**Comment by Kasshern** [comment]
@chaals @Therecanbeonlyone1969 This is just an issue I created for the purposes of tracking work since my feature branch is named according to issue number. Here "Testability Requirements" refers to our internal requirement for testability statements. I can see how the wording is confusing, will edit.
