### ISSUE TITLE
Baseline Protocol Standards -  Scope Completeness project

### ISSUE THREAD

**Issue by Consianimis** [eea-oasis/baseline-standard#51]
**#Objective**
Need for a pair or small group dedicated to ensuring that we have established an extensive and complete scope i.e. that we cover everything. Go as far as we can go including reference architectures. To be completed by the 6th May.

**Comment by Consianimis** [comment]
@humbitious  - Please list all the individuals you would like to work on this. Then let us send an email to them with a proposed date for a 1 hour meeting next week and another 1 hour meeting the week after. The time between the two meetings will allow individuals to think and do some homework if any has been identified. Thanks.

**Comment by humbitious** [comment]
Here's the list:

@Therecanbeonlyone1969 
@bitwiseguy 
@kthomas 
Lucas Rodriguez (can't find his github ID)
@skarred14 
Mehran or Alessandro from SAP.

Will send note now.  (Wish there were an easy way to find a time to meet, but will use the old "when can everyone meet" round-robin.)

**Comment by mehranshakeri** [comment]
@humbitious  I can join from SAP side

**Comment by humbitious** [comment]
Notes from "Features and Non-Functional Requirements to Consider for V1" Sessions, conducted during The Baseline show sessions in May 2021:

Debasing and Rebasing
Revisioning
n-lateral Workstep Support (workstep policy)
Ensure Workflow is strictly deterministic
Ability to go from a baselined record to a token
Relevance mapping (lots of fields but we are only 'baselining' field x and y)
Integration of real contracts systems
ERP to CRM connections.
Approaches for notating and managing the "why" of a state change, particularly in supply chain.

**Comment by Consianimis** [comment]
**To be considered for Standard:**
Debasing and Rebasing:
Revisioning
n-lateral Workstep Support (workstep policy)
Ensure Workflow is strictly deterministic

**Implementation specific:**
Relevance mapping (lots of fields but we are only 'baselining' field x and y)
Integration of real contracts systems
ERP to CRM connections.
Approaches for notating and managing the "why" of a state change, particularly in supply chain.

**Outside of the scope?**
Ability to go from a baselined record to a token  - We need another spec ?

**Comment by humbitious** [comment]
Support for VANs?

What if someone is using NATS and another is on, say, an older value added network or a different messaging network...how to easily do discovery and integration.

**Comment by kthomas** [comment]
> Notes from "Features and Non-Functional Requirements to Consider for V1" Sessions, conducted during The Baseline show sessions in May 2021:
> 
> Debasing and Rebasing

Should be covered by existing APIs with some color commentary in the implementation guide.

> Revisioning

Covered by existing privacy package.

> n-lateral Workstep Support (workstep policy)

Covered by leveraging workgroups and workflows properly-- fodder for implementation guide?

> Ensure Workflow is strictly deterministic

This is covered by existing methodology; however implementation guide should discuss some pitfalls and/or caveats.

> Ability to go from a baselined record to a token

@Therecanbeonlyone1969

> Relevance mapping (lots of fields but we are only 'baselining' field x and y)

Supported by current APIs; probably implementation-specific and not considered by standard.

> Integration of real contracts systems

Out of scope, IMO. Supported with existing APIs.

> ERP to CRM connections.

Out of scope, IMO. Supported with existing APIs.

> Approaches for notating and managing the "why" of a state change, particularly in supply chain.

Out of scope, IMO.

**Comment by mehranshakeri** [comment]
Part of standard
- n-lateral Workstep Support (workstep policy) 
- Ensure Workflow is strictly deterministic


Need more details
- Debasing and Rebasing (recovery?)
- Revisioning (recovery?)
- Approaches for notating and managing the "why" of a state change, particularly in supply chain.
- Relevance mapping (lots of fields but we are only 'baselining' field x and y)
- Integration of real contracts systems

Out of scope
- ERP to CRM connections


I have some ideas how to share objects like business documents (State Objects I think) in a notarized way but efficient. Also how to create connections among those objects to create a graph of dependency. If interested I can elaborate more and have your feedbacks.

**Comment by mehranshakeri** [comment]
> Would love to hear about your ideas for notarized business document sharing


Ready for feedbacks #55

**Comment by humbitious** [comment]
Ok, I've reviewed the footage from the baseline shows, and unless others have spotted things that were covered that we missed, this thread looks to cover it.  That said, what we don't really have, imo, is a clear roadmap of what shall be a) implemented for v1; b) considered a final standards draft.   

We need a clear set of Issues/Tasks/Acceptance Criteria and clear resourcing across the companies to push in getting it done. I think we're close, and while we will miss June 1 for this, we should be able to get it locked in with a couple meetings...and an influx of people (some of whom I'm hiring right now) to spend the summer/fall focused on producing a professional v1.

Hope to have our new project manager for baselining hired in June. As that happens, will have them a) help the community write, prioritize, maintain and close Issues; b) run regular joint development sync sessions (light scrum); c) turbocharge the grants/bounties process to get stuff done that needs to be paid work outside the employees of the contributing companies.

I'm not convinced about how >2 parties in a workstep is not somethign we shouldn't prioritize, and I don't agree that it is an implementation detail by any means.  It's fundamental, essential, and not obvious how to make it elegant for developers.  Also, the privacy package and persistence packages need a lot of cleaning, from what I'm hearing from newbie developers.

**Comment by Consianimis** [comment]
In scope:

To do:
Debasing and Rebasing
Revisioning
n-lateral Workstep Support (workstep policy) - multi lateral more than 2 parties

Already addressed:
Ensure Workflow is strictly deterministic
Relevance mapping (lots of fields but we are only 'baselining' field x and y)
