### ISSUE TITLE
Multi-Party Document Sharing - Notarization & Confidentiality

### ISSUE THREAD

**Issue by mehranshakeri** [eea-oasis/baseline-standard#55]
## Problem

A simplified picture of supply chain looks like this:

<img width="738" alt="full-picture" src="https://user-images.githubusercontent.com/14055200/118242940-2a278e80-b49e-11eb-8b69-dce5487bdf08.png">

_Figure1 - Full Picture_

The arrows show the direction and flow of data from upstream to downstream parties. Usually there is at least one authority/auditor interested in the full picture but members are usually aware of the communication with their direct business partner. However, in some scenarios they are interested in some degree of (limited) visibility in n-tier supply chain information. e.g. in which markets my goods end up being sold or where do my raw materials come from?

Having heterogeneous systems of records and communication channels result in
- low/no transparency on the supply chain of products and materials
- isolating material traceability information in separate systems, un-shareable with involved participants

What we try to enable is the possibility to
- Record and build graphs of product genealogy relationships
- Seamless tracking of all sourced materials securely and verifiable
- Maintaining confidentiality by sharing transaction information only with the participants directly involved in a transaction

e.g. In a product level, a desired visibility of a manufacturer could be:
<img width="749" alt="product-level" src="https://user-images.githubusercontent.com/14055200/118245936-a53e7400-b4a1-11eb-8e37-11b6d59b328d.png">

Figure2 - Product's genealogy graph with limited n-tier visibility

where a manufacturer has full visibility on all the information shared with his/her direct partners but limited visibility on downstream. 

> Must be noted that sharing any information is optional and requires consent from all the involved parties and the data owner

## Notarization

To manage the versioning of a document (contract, ...) we can simply notarize its hash and in case of any change, notarize the new hash by nullifying the latest hash. Needless to say the document itself will remain in local (private) systems of records accessible only by its owner.

Notarization of a document is a mapping between the document's hash and its owner's identifier. The identifier could be a  public key or address (asymmetric cryptography).

E.g. if the hash of our document is 0xaaaaaaaaaa and the owner is identified as 0x11111111, then the notary will persist the mapping between this document and its owner.

Adopting UTXO data structure, a notarization transaction includes some inputs and some outputs. Inputs will be the existing documents intended to be replaced by new documents provided in the outputs.

**Notarizing a new document** will be used when it will be a root of relationship graph. Inputs will be empty, and the outputs will include the document hash and its owner.

```
{
  inputs: [],
  outputs: [
    {
      hash: 0xaaaaaaaaaa,
      owner: 0x11111111
    }]
}

```
**Notarizing change of ownership** is used to transfer the ownership of document to a new owner. The existing notarized document’s hash will be included in the inputs and the outputs must include the new owner. This transaction must carry the signature from the current owner. The output hash might be the same as input or differ.

```
{
  inputs: [
    0xaaaaaaaaaa
  ],
  outputs: [
    {
      hash: 0xaaaaaaaaaa,
      owner: 0x22222222	// new owner
    }]
}

```
**Notarizing a new version** of existing document will notify everyone about a new version of the existing document. The current version must be replaced by the new version.

```
{
  inputs: [
    0xaaaaaaaaaa
  ],
  outputs: [
    {
      hash: 0xccccccccc,	// hash of new version of the document
      owner: 0x11111111
    }]
}

```
**Notarizing granting access** is a way to enable other parties to grow the graph of relationships. Let’s say we have a product ready to ship. The owner of the product must be able to grant access to the shipping company to attach shipping documents without losing the ownership on the product itself. This type of notarization generates an output which is a placeholder for future documents owned by another entity while keeping the ownership of the current document preserved.

```
{
  inputs: [
   0xaaaaaaaaaa
  ],
  outputs: [
    {
      hash: 0xaaaaaaaaaa,
      owner: 0x11111111
    }, {
      hash: 0xbbbbbbbbb,	// the placeholder
      owner: 0x33333333
    }]
}

```
Later on, the other entity can use Notarizing new version to attach the relevant document to the graph.

```
{
  inputs: [
    0xbbbbbbbbb
  ],
  outputs: [
    {
      hash: 0xqqqqqqqq,	// replacing the placeholder by real document’s hash
      owner: 0x33333333
    }]
}

```

Since all notarization transactions happen on a common notary, anyone is able to observe and build the graph independently. But no sensitive information will be available. To get the original document, either the source can proactively send it to the relevant partner(s) or partner(s) can request this when they observe any change on the notary. When necessary, even this relationship could be hidden behind ZKP shielding and document hashes will be shared off-chain. However, to nullify an old version, that hash could be marked publicly as a burnt hash without revealing any extra information.

## Integrated Document Relation

The notarization concept allows independent documents to be linked externally. Meaning the relationships are not part of the document itself but on a higher level. An alternative approach could be having these relationships as part of the document itself.

e.g.
```
{
  documentType: "mainContract",
  relevantDocs: {
    orderItems: 0xa1a1a1a1,       // placeholder for line items document
    shippingDoc: 0x12345,       // placeholder for shipping document
  }
}
```
Placeholder is a random hash which will be changed in the future to the hash of real document containing the exact data.

> In any cases, if a document requires confirmation from counterparts, the notarization object can be proposed by any of them but must be signed by all.

## Visibility

Once a document is notarized, we should be able to share different parts of it with different parties without revealing more than its needed. To do so, we breakdown the document to a list of flat key/value pairs, list all the keys in the first leaf in a Merkle tree, list all the values in the same order as their keys appear in the first leaf, add nonces to prevent any brut-force attempt and use the Merkle tree root hash as the document hash to be notarized. 

To get rid of nested keys, we merge the sub-key and its main-key with a `.` delimiter as `main-key.sub-key`.

from
```
{
  main-key: {
    sub-key: value
  }
}

```
to 
```
{
  main-key.sub-key: value
}

```

All the keys will be concatenated using `,` delimiter in one string and will be used as the first leaf in the Merkle tree. This prevents having more than one leaf with the same key or more than a value for the same key. We assume the delimiter doesn't occur in the main string, otherwise must be replaced or escaped properly.

Values will be listed as the next leaves in the same order that their keys appear in the first leaf.  The list of ordered tree leaves will look like this:

```
[
  "0": "Buyer,Seller,Product.Name,Price"
  "1": "Alice",
  "2": "Bob",
  "3": "CoolestProduct",
  "4": "1000euros"
]
```

Each leaf will receive an independent random nonce and the Merkle tree root will be calculated and notarized. 

At this stage, anyone with access to the main data can share different parts of the same Merkle tree and receiving parties are able to verify that they are talking about the same notarized document, although they might not see all the information. There will be only a single notarization transaction and receiving parties can also re-share different views without any need to have another separate notarization transaction. This also enables all the counterparts to be aware of any changes that might be applied to the notarized document and request the exact changes. If they are authorized to see the changes, they will receive the exact changed data, otherwise only enough hashes from the Merkle tree to validate that their relevant information has been kept intact.

**Comment by humbitious** [comment]
First, this should get the award for this quarter's most well-written, clear explanation of a complex topic.  Outstanding writeup.  I'm keen to hear what others think, but I found myself quite interested in the notion of how to not only keep the data private, which this pattern clearly handles, but also preventing a powerful ML/AI approach from developing classifiers from large amounts of ongoing activity on the ledger, assuming the ledger is public or the attacker has access to a node.  This is where I expect there is nice synergy with the shield/verifier/merkle trie approach in the baseline spec could help this pattern for notarized information compartmentalization.

**Comment by mohanramanujam** [comment]
I found this infographics from a HBR article which was informative. If useful to add, a citation to the source may be needed. [https://hbr.org/2020/05/building-a-transparent-supply-chain]. 
[hbr-supplychain blockchain - addendum 1 - R2003F_GAUR_CAPTURING.pdf](https://github.com/ethereum-oasis/baseline-standard/files/6502017/hbr-supplychain.blockchain.-.addendum.1.-.R2003F_GAUR_CAPTURING.pdf)

**Comment by Consianimis** [comment]
Notorization & Confidentiality can be addressed with VC. When specific use cases related to visibility will be surfaced, issue can be reopened.
