### ISSUE TITLE
Consider explaining the brackets like [R1] in Typographical Conventions

### ISSUE THREAD

**Issue by OASIS-OP-Admin** [eea-oasis/baseline-standard#67]
Looking at the bracketed numbers, e.g. [R1] or [D1], they look like they might be numbered requirements, maybe tied to the conformance clauses. I think it would help to explain what they mean in the Typo Conventions section.

**Comment by Consianimis** [comment]
@OASIS-OP-Admin  - Done in PR#63 : https://github.com/eea-oasis/baseline-standard/pull/63/commits/e0bb3da000ced73082ef55a853f790b78cb29068
