### ISSUE TITLE
Fill out the Acknowledgments section 

### ISSUE THREAD

**Issue by OASIS-OP-Admin** [eea-oasis/baseline-standard#68]
Not critical for Project Specification Draft stage but it will be needed when the work gets approved as a Project Specification. The Acknowledgements appendix should have the list filled out of everyone who contributed to the work.

**Comment by Consianimis** [comment]
Done in PR63: https://github.com/eea-oasis/baseline-standard/pull/63/commits/33b176223769bc2b97a65ac258bbdb172bc9ebbf and https://github.com/eea-oasis/baseline-standard/pull/63/commits/d1462742f5a6de6fb4381e32c8bfda9c879aa89d
