### ISSUE TITLE
Grammar issues in the Glossary for Verifiably Secure

### ISSUE THREAD

**Issue by tkuhrt** [eea-oasis/baseline-standard#85]
> Verifiably Secure:
> 
> Verifiable computing that can be described as verifiably secure enables a computer to offload the computation of some function to other perhaps untrusted clients, while maintaining verifiable, and thus secure results. 

The grammar in the baseline-core-v1.0-psd01.md glossary for "Verifiably Secure" needs to be corrected.

**Comment by Therecanbeonlyone1969** [comment]
@tkuhrt ... which grammar rule was violated? Missed two commas on "thus". Recommend you make a rewording proposal..

**Comment by tkuhrt** [comment]
Two verbs. Maybe something like "Verifiably secure enables a computer to offload the computation of some function to other perhaps untrusted clients, while maintaining verifiable, and thus secure results"

**Comment by Therecanbeonlyone1969** [comment]
Proposal: "A Process that enables a computer to offload the computation of some function to other perhaps untrusted clients, while maintaining verifiable, and, thus, secure results."

**Comment by Therecanbeonlyone1969** [comment]
@tkuhrt please, see the updated definition (based on my proposal above) in the new working branch https://github.com/eea-oasis/baseline-standard/blob/pr/101/core/baseline-core-v1.0-psd01.md ...  and let us know if ok.

**Comment by tkuhrt** [comment]
LGTM

**Comment by Therecanbeonlyone1969** [comment]
done with #114
