### ISSUE TITLE
Glossary item for "Workgroup" does not exist

### ISSUE THREAD

**Issue by tkuhrt** [eea-oasis/baseline-standard#86]
It would be good to have a glossary item for "Workgroup", which is referred to in many of the other glossary items, and I am sure throughout the specification.

**Comment by Therecanbeonlyone1969** [comment]
@tkuhrt thank you for the catch. Will be included in a clean up PR shortly.

**Comment by Therecanbeonlyone1969** [comment]
@tkuhrt 

**Workgroup**

A workgroup is defined through a set of authorized users of a BPI, referred to as BPI Subjects in this document, one or more security policies, a well-defined administrator role and its association with one or more worksteps through a workflow to achieve system of record synchronization of the workgroup participants.

see also glossary section of this working branch https://github.com/eea-oasis/baseline-standard/blob/pr/101/core/baseline-core-v1.0-psd01.md

**Comment by Therecanbeonlyone1969** [comment]
done with #114
