### ISSUE TITLE
Discrepancy between the number of requirement levels and the number specified

### ISSUE THREAD

**Issue by tkuhrt** [eea-oasis/baseline-standard#87]
> There are four requirement levels that are coded in requirement ids as per below convention:
> 
> [R] - The requirement level for requirements which IDs start with the letter R is to be interpreted as MUST as described in RFC2119.
> [D] - The requirement level for requirements which IDs start with the letter D is to be interpreted as SHOULD as described in RFC2119.
> [O] - The requirement level for requirements which IDs start with the letter O is to be interpreted as MAY as described in RFC2119.

In the first sentence, it says that there are "four" requirement levels, but only "three" are listed.

**Comment by tkuhrt** [comment]
Maybe [CR] is the fourth, but it is not clear from the way the document is written that this is the fourth requirement level.

**Comment by Therecanbeonlyone1969** [comment]
The header 1.3.2 should be removed to make it clear. Will be done in another clean up PR. Also, would be great if you could make a rewording suggestion that makes sense to you. @tkuhrt
