### ISSUE TITLE
make requirements linkable

### ISSUE THREAD

**Issue by chaals** [eea-oasis/baseline-standard#90]
Markdown is not helpful here, but writing them as e.g.

````
#### [R43]
Make it possible to link to a requirement, instead of having to point people to the document and then ask them to search for the relevant bit by themselves
````

would enable links like `..spec.html#[r43]` to work

**Comment by Therecanbeonlyone1969** [comment]
@chaals ... you are more than welcome to do a PR with that change, if you feel strongly about it.

**Comment by Therecanbeonlyone1969** [comment]
@GoldenBit0 @mehranshakeri and @Therecanbeonlyone1969 ... will take this on. @chaals, you are strongly encouraged to participate in this effort in this [branch](https://github.com/eea-oasis/baseline-standard/blob/pr/101/core/baseline-core-v1.0-psd01.md)

**Comment by BriannaMRich** [comment]
@chaals looking for confirmation on the request. Are you looking for the requirements section to be linked - so when they are referred to within the specification and/or outside. See below for example. If this is accurate please let us know :) 

[**[R34]** The identifiers and identity utilized in a BPI MUST be controlled by its Principal Owner.](https://github.com/eea-oasis/baseline-standard/blob/main/core/baseline-core-v1.0-psd01.md?plain=1#L721)

@GoldenBit0

**Comment by chaals** [comment]
@BriannaMRich Exactly!

**Comment by BriannaMRich** [comment]
@chaals Great!! @GoldenBit0 FYI

**Comment by Therecanbeonlyone1969** [comment]
@chaals ... that is an absolute (to line 721) not a relative (R34) reference. We do need relative references, however.

cc @BriannaMRich ... see the above-referenced branch for relative links.

**Comment by mehranshakeri** [comment]
Is this already done? I see all the links are already fixed. If not, could you please guide me to where still needs review/correction?

**Comment by Therecanbeonlyone1969** [comment]
> Is this already done? I see all the links are already fixed. If not, could you please guide me to where still needs review/correction?

@mehranshakeri ... yes in the branch pr/101 ... as soon as the API spec .md file has been brought in alignment with the yaml we will do a PR

**Comment by Therecanbeonlyone1969** [comment]
done with #114
