### ISSUE TITLE
Define identity-associated data, not Identity

### ISSUE THREAD

**Issue by chaals** [eea-oasis/baseline-standard#91]
There is no need to have a definition of a term used like the dictionary says.

The important term is `identity-associated data', and the relevant snippet from the existing definition:

> Identity-associated data consists of signed certificates or credentials such as verifiable credentials and other unsigned, non-verifiable data objects generated by or on behalf of the unique identifier(s).

Is sufficient...

**Comment by Therecanbeonlyone1969** [comment]
But identity is not constructed as the dictionary says, because the dictionary is mute on that point. Hence, the programmatic definition of identity how it is used in the Baseline Protocol is more than warranted.

**Comment by Therecanbeonlyone1969** [comment]
@chaals ... will close the issue at the next standards meeting, unless commented on by you before the next standards meering.

**Comment by Therecanbeonlyone1969** [comment]
clarified language in #114
