### ISSUE TITLE
Overview repeats the ToC twice

### ISSUE THREAD

**Issue by chaals** [eea-oasis/baseline-standard#92]
The overview section is one part overview f the document, but that is really just a restatement of the table of contents, adding to the redundancy by listing most of the section contents in the first line about the section and then again in a list.

Removing this whole list would trim the document down for easier reading with no appreciable loss of information or legibility.

**Comment by Therecanbeonlyone1969** [comment]
Not uncommon practice in standards to have a ToC and repeat the main sections and some or all subsections with some clarification what they represent, which the expansion of the ToC in the overview does. cc @chaals

**Comment by Therecanbeonlyone1969** [comment]
@chaals ... per WG meeting 11/18/2021, repetition is warranted. Closing issue.
