### ISSUE TITLE
Are [R1], [R2], and [R3] redundant?

### ISSUE THREAD

**Issue by chaals** [eea-oasis/baseline-standard#93]
The first three requirements are about some kind of agreement.

It's not clear why any agreement is necessary unless there is a transaction. In that case, it is not clear what the difference is between the three requirements - can they merged?

**Comment by Therecanbeonlyone1969** [comment]
Nope they are not. See my comment on PR #89. cc @chaals

**Comment by Therecanbeonlyone1969** [comment]
closing issue ... related PR #89 merged.
