### ISSUE TITLE
Image illustrating 5.5 is illegible

### ISSUE THREAD

**Issue by chaals** [eea-oasis/baseline-standard#94]
It seems that the image uses a semi-transparent background, but laid over a black background this makes it impossible to read.

**Comment by Therecanbeonlyone1969** [comment]
I can read it just fine. @mehranshakeri could you produce a higher resolution image?

**Comment by mehranshakeri** [comment]
Sure, I will try. I used default settings from drawio. Source file is also [here](https://github.com/mehranshakeri/baseline-standard/blob/aeb6a165a161cfe74f22a20e8ec75c305571d974/core/images/BPI-integration-5.5.drawio.png)
I will work on it to see if I can improve it.

**Comment by chaals** [comment]
The problem is not resolution, it is background. I'll have a go at a fix, if you want to assign me.

**Comment by mehranshakeri** [comment]
I appreciate it if you could take over.

**Comment by chaals** [comment]
PR #101 changes the transparent background so the image can be read on any background. (That's all it does)

**Comment by chaals** [comment]
(fixed up other images with the same issue, too)
