### ISSUE TITLE
[R114] Define "JSON-LD format sympathetic"

### ISSUE THREAD

**Issue by chaals** [eea-oasis/baseline-standard#95]
R114 requires that messages are "JSON-LD format sympathetic", but it is not stated what that means in the spec, nor is that term used in the JSON-LD spec.

Please define the meaning, or change the requirement.

**Comment by Therecanbeonlyone1969** [comment]
There is a reference given as to what it means. We can repeat that in the glossary if that is required. I think a reference is sufficient. 

cc @chaals

**Comment by chaals** [comment]
The reference says what JSON-LD means, and that is sufficient. But I cannot find the term "format sympathetic" defined in either this spec or the JSON-LD spec.

Either defining it in the glossary, in the requirement, or changing the wording, would be helpful.

If it means "either a valid  JSON-LD document, or a JSON document that can be interpreted as JSON-LD by associating a context through HTTP headers, as described in https://www.w3.org/TR/json-ld11/#interpreting-json-as-json-ld" then we should make an explicit reference to that section of the JSON-LD spec.

**Comment by Therecanbeonlyone1969** [comment]
@chaals ... very good wording. will include in PR I am working on ... see current working branch for PR https://github.com/eea-oasis/baseline-standard/blob/pr/101/core/baseline-core-v1.0-psd01.md

**Comment by Therecanbeonlyone1969** [comment]
closing issues per meeting 12/2
