### ISSUE TITLE
[CR25] is redundant

### ISSUE THREAD

**Issue by chaals** [eea-oasis/baseline-standard#96]
The upshot of the requirements is that If you implement D34 you have to implement CR25, but that is the same as implementing [D34] anyway.

Propose removing [CR25]

**Comment by Therecanbeonlyone1969** [comment]
Nuance here. It is actually necessary. If you implement D34, you might start a workflow with 2 worksteps and they use the same prover system. Then you update the workflow with a 3rd workstep, you could choose then a different prover system, Breaking the requirement and screwing things up. Therefore, if you commit to using one prover system for a workflow, you cannot ever change your mind, if you want to be compliant. If you change the prover system (a very bad idea, as this might be done maliciously), you are no longer compliant. So this is a safety precaution that an implementation choosing to implement [D34] must put in programmatic constraints that a prover system cannot be changed mid workflow.  

cc @chaals

**Comment by Therecanbeonlyone1969** [comment]
@chaals ... will add above comment in appropriate form as an explanatory text below [CR25].
