### ISSUE TITLE
[R309] is under-specified

### ISSUE THREAD

**Issue by chaals** [eea-oasis/baseline-standard#98]
What are the required characteristics to pass?

**Comment by Therecanbeonlyone1969** [comment]
Good point. Please, make a suggestion for correction. @chaals

**Comment by Therecanbeonlyone1969** [comment]
@rfisch to make a proposal for common and measurable characteristics for enterprise database systems.

**Comment by Therecanbeonlyone1969** [comment]
@chaals ... added several, measurable characteristics to R309 ... see https://github.com/eea-oasis/baseline-standard/blob/pr/101/core/baseline-core-v1.0-psd01.md#751-bpi-storage-centralized-deployment

**Comment by Therecanbeonlyone1969** [comment]
done with #114
