### ISSUE TITLE
conformance levels 4-6 can't be achieved

### ISSUE THREAD

**Issue by chaals** [eea-oasis/baseline-standard#99]
(It says so in the spec).

Propose to remove them - it's not clear what they add, apart from clarifying that there is work to be done before they might be a useful concept.

**Comment by Therecanbeonlyone1969** [comment]
sorry, i do not understand. this is merely stating that these are the levels and what is required to achieve them. That they currently cannot be achieved is not relevant, since they will be achievable in the future. They add clarification that there are more levels of conformance.

**Comment by chaals** [comment]
I'm generally wary of a spec predicting the future in anything but a very open-ended way. I'd rather keep the note that we expect in the future to have tests, and say the conformance to a later version might require passing them.

Because we *might* decide something different is what the industry needs, before we get to the future we're currently promising to deliver.

I'm also not a fan because it seems like the numbering suggests 4 is better than 3 whereas in practice it's not obvious that would be true.

**Comment by Therecanbeonlyone1969** [comment]
@chaals ... the TSC is raising funds for a grant to create the test fixture and test harness, so this is not far away future but Q1/Q2 of 2022.

**Comment by Therecanbeonlyone1969** [comment]
@chaals ... will you make a PR with the new language as you volunteered during the Standards WG call on 12/17/2021?
